### ISSUE TITLE
Github Server Return Error

### ISSUE THREAD

**Issue by SatyricL** [gw2-addon-loader/GW2-Addon-Manager#197] opened 2022-09-18 05:47 UTC
I read some old reports of this same issue happening and it was said that this error occurs from opening the add on manager too many times, however this cant be the case for me, since its the first time I opened it on about a month.

![gw2AOMissue](https://user-images.githubusercontent.com/113817831/190887734-71638f54-34f5-4215-9a7e-0ed530a98277.png)

Update:
Running as administrator seems to circumvent the error message.

**Comment by knoxfighter** [comment] 2022-09-18 12:57
duplicate of #195

**Closed** 2022-09-18 15:59 UTC
Labels: bug
